spring:
  application:
    name: homeWorkLevel3
  main:
    banner-mode: 'OFF'
  #hw-6
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

#hw-5
application:
  cash:
    enable: 'true'